; Generated by Lang compiler

extern GetCommandLineA
extern ExitProcess

section .code
global _start
_start:
    call GetCommandLineA
    mov r10, rax
    xor rcx, rcx
    sub rsp, 8 * 64 ; Max 64 command line args
    mov rdx, rsp
    arg_loop_top:
    mov bl, BYTE [rax]
    test bl, bl
    jz arg_loop_exit
    cmp bl, ' '
    jne arg_loop_next
    cmp r10, rax
    je skip
    mov BYTE [rax], 0
    mov QWORD [rdx], r10
    add rdx, 8
    inc rcx
    skip:
    mov r10, rax
    inc r10
    arg_loop_next:
    inc rax
    jmp arg_loop_top
    arg_loop_exit:
    mov al, BYTE [r10]
    cmp al, ' '
    je args_done
    cmp al, 0
    je args_done
    mov QWORD [rdx], r10
    inc rcx
    args_done:
    mov rdx, rsp
    sub rsp, 32
    call main
    mov ecx, eax
    call ExitProcess

main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 32 ; reserve stack space for 3 locals
    
    ; let i: i32; i = 1234;
    lea rbx, QWORD [rbp + -32] ; get address of 'i'
    mov r10, 1234
    mov DWORD [rbx], r10d
    
    ; let ptr_int: i32*; ptr_int = &i;
    lea rbx, QWORD [rbp + -32] ; get address of 'i'
    lea r10, QWORD [rbp + -24] ; get address of 'ptr_int'
    mov QWORD [r10], rbx
    
    ; let ptr_char: u8*; ptr_char = cast(u8*) ptr_int;
    mov rbx, QWORD [rbp + -24]
    lea r10, QWORD [rbp + -16] ; get address of 'ptr_char'
    mov QWORD [r10], rbx
    
    ; *(ptr_char + 0) = cast(u8) 13
    mov rbx, QWORD [rbp + -16]
    mov r10, 0
    add rbx, r10
    mov r10, 13
    mov BYTE [rbx], r10b
    
    ; *(ptr_char + 1) = cast(u8) 12
    mov rbx, QWORD [rbp + -16]
    mov r10, 1
    add rbx, r10
    mov r10, 12
    mov BYTE [rbx], r10b
    
    ; *(ptr_char + 2) = cast(u8) 11
    mov rbx, QWORD [rbp + -16]
    mov r10, 2
    add rbx, r10
    mov r10, 11
    mov BYTE [rbx], r10b
    
    ; *(ptr_char + 3) = cast(u8) 10
    mov rbx, QWORD [rbp + -16]
    mov r10, 3
    add rbx, r10
    mov r10, 10
    mov BYTE [rbx], r10b
    
    ; return i
    movsx rbx, DWORD [rbp + -32]
    mov rax, rbx ; return via rax
    jmp L_function_main_exit
    
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    


section .data
