; Generated by Lang compiler

extern GetCommandLineA
extern ExitProcess

section .code
global _start
_start:
    call GetCommandLineA
    mov rcx, rax
    call main
    mov ecx, eax
    call ExitProcess

extern DoesNotExist

main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    
    ; DoesNotExist(48879)
    sub rsp, 32 ; reserve shadow space and 1 arguments
    mov rbx, 48879
    mov rcx, rbx ; arg 1
    call DoesNotExist
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    


section .data
