; Generated by Lang compiler

extern GetCommandLineA
extern ExitProcess

section .code
global _start
_start:
    call GetCommandLineA
    mov rcx, rax
    call main
    mov ecx, eax
    call ExitProcess

extern puts

extern strlen

main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 16 ; reserve stack space for 1 locals
    
    ; let str: u8*; str = "Hello world!";
    lea rbx, QWORD [rbp + -16] ; get address of 'str'
    lea r10, [REL lit_str_0]
    mov QWORD [rbx], r10
    
    ; puts(str)
    sub rsp, 32 ; reserve shadow space and 1 arguments
    mov rbx, QWORD [rbp + -16]
    mov rcx, rbx ; arg 1
    call puts
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    ; return strlen(str)
    sub rsp, 32 ; reserve shadow space and 1 arguments
    mov rbx, QWORD [rbp + -16]
    mov rcx, rbx ; arg 1
    call strlen
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    mov rax, rbx ; return via rax
    jmp L_function_main_exit
    
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    


section .data
lit_str_0 db "Hello world!", 0
