; Generated by Lang compiler

GLOBAL main

SECTION .code
EXTERN GetProcessHeap

EXTERN HeapAlloc

EXTERN HeapFree

EXTERN CopyMemory

EXTERN ExitProcess

assert:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov BYTE [rbp + 16], cl ; push arg 0 
    movzx rbx, BYTE [rbp + 16]
    xor rbx, -1
    and rbx, 1
    cmp rbx, 0
    je L_exit1
        sub rsp, 32 ; reserve shadow space and 1 arguments
        mov rbx, 1
        mov rcx, rbx ; arg 1
        call ExitProcess
        add rsp, 32 ; pop arguments
        mov rbx, rax ; get return value
        
    L_exit1:
    
    xor rax, rax ; Default return value 0
    L_function_assert_exit:
    mov rsp, rbp
    pop rbp
    ret
    



malloc:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov DWORD [rbp + 16], ecx ; push arg 0 
    mov rbx, QWORD [REL heap]
    mov r10, QWORD [REL NULL]
    cmp rbx, r10
    sete bl
    and bl, 1
    movzx rbx, bl
    cmp rbx, 0
    je L_exit2
        sub rsp, 32 ; reserve shadow space and 0 arguments
        call GetProcessHeap
        add rsp, 32 ; pop arguments
        mov rbx, rax ; get return value
        lea r10, QWORD [REL heap] ; get address of 'heap'
        mov QWORD [r10], rbx
        
    L_exit2:
    
    sub rsp, 32 ; reserve shadow space and 3 arguments
    mov rbx, QWORD [REL heap]
    mov rcx, rbx ; arg 1
    mov rbx, 0
    mov rdx, rbx ; arg 2
    movsx rbx, DWORD [rbp + 16]
    mov r8, rbx ; arg 3
    call HeapAlloc
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    mov rax, rbx ; return via rax
    jmp L_function_malloc_exit
    
    xor rax, rax ; Default return value 0
    L_function_malloc_exit:
    mov rsp, rbp
    pop rbp
    ret
    

free:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    sub rsp, 32 ; reserve shadow space and 1 arguments
    mov rbx, QWORD [rbp + 16]
    mov r10, QWORD [REL NULL]
    cmp rbx, r10
    setne bl
    and bl, 1
    movzx rbx, bl
    mov rcx, rbx ; arg 1
    call assert
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 1 arguments
    mov rbx, QWORD [REL heap]
    mov r10, QWORD [REL NULL]
    cmp rbx, r10
    setne bl
    and bl, 1
    movzx rbx, bl
    mov rcx, rbx ; arg 1
    call assert
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 3 arguments
    mov rbx, QWORD [REL heap]
    mov rcx, rbx ; arg 1
    mov rbx, 0
    mov rdx, rbx ; arg 2
    mov rbx, QWORD [rbp + 16]
    mov r8, rbx ; arg 3
    call HeapFree
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    xor rax, rax ; Default return value 0
    L_function_free_exit:
    mov rsp, rbp
    pop rbp
    ret
    

EXTERN GetStdHandle

EXTERN WriteFile

EXTERN strlen


print:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    mov DWORD [rbp + 24], edx ; push arg 1 
    sub rsp, 16 ; reserve stack space for 2 locals
    sub rsp, 32 ; reserve shadow space and 1 arguments
    movsx rbx, DWORD [REL STD_OUTPUT_HANDLE]
    mov rcx, rbx ; arg 1
    call GetStdHandle
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    lea r10, QWORD [rbp + -16] ; get address of 'std_handle'
    mov QWORD [r10], rbx
    
    mov DWORD [rbp + -8], 0 ; zero initialize 'bytes_written'
    
    sub rsp, 48 ; reserve shadow space and 5 arguments
    mov rbx, QWORD [rbp + -16]
    mov rcx, rbx ; arg 1
    mov rbx, QWORD [rbp + 16]
    mov rdx, rbx ; arg 2
    movsx rbx, DWORD [rbp + 24]
    mov r8, rbx ; arg 3
    lea rbx, QWORD [rbp + -8] ; get address of 'bytes_written'
    mov r9, rbx ; arg 4
    mov rbx, 0
    mov QWORD [rsp + 32], rbx ; arg 5
    call WriteFile
    add rsp, 48 ; pop arguments
    mov rbx, rax ; get return value
    
    xor rax, rax ; Default return value 0
    L_function_print_exit:
    mov rsp, rbp
    pop rbp
    ret
    

print_num:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov DWORD [rbp + 16], ecx ; push arg 0 
    sub rsp, 32 ; reserve stack space for 5 locals
    lea rbx, QWORD [rbp + -32] ; get address of 'num_str'
    lea r10, [REL lit_str_3]
    mov QWORD [rbx], r10
    
    lea rbx, QWORD [rbp + -24] ; get address of 'idx'
    mov r10, 0
    mov DWORD [rbx], r10d
    
    L_loop3:
    movsx rbx, DWORD [rbp + 16]
    mov r10, 0
    cmp rbx, r10
    setg bl
    and bl, 1
    movzx rbx, bl
    cmp rbx, 0
    je L_exit3
        movsx rbx, DWORD [rbp + 16]
        mov r10, 10
        mov rax, rbx
        cqo
        idiv r10
        mov rbx, rdx
        lea r10, QWORD [rbp + -20] ; get address of 'digit'
        mov BYTE [r10], bl
        
        mov rbx, QWORD [rbp + -32]
        movsx r10, DWORD [rbp + -24]
        add rbx, r10
        movzx r10, BYTE [rbp + -20]
        mov r11, 48
        add r10, r11
        mov BYTE [rbx], r10b
        
        movsx rbx, DWORD [rbp + 16]
        mov r10, 10
        mov rax, rbx
        cqo
        idiv r10
        mov rbx, rax
        lea r10, QWORD [rbp + 16] ; get address of 'num'
        mov DWORD [r10], ebx
        
        movsx rbx, DWORD [rbp + -24]
        mov r10, 1
        add rbx, r10
        lea r10, QWORD [rbp + -24] ; get address of 'idx'
        mov DWORD [r10], ebx
        
    jmp L_loop3
    L_exit3:
    
    lea rbx, QWORD [rbp + -16] ; get address of 'i'
    mov r10, 0
    mov DWORD [rbx], r10d
    
    L_loop4:
    movsx rbx, DWORD [rbp + -24]
    mov r10, 2
    mov rax, rbx
    cqo
    idiv r10
    mov rbx, rax
    movsx r10, DWORD [rbp + -16]
    cmp r10, rbx
    setl r10b
    and r10b, 1
    movzx r10, r10b
    cmp r10, 0
    je L_exit4
        mov rbx, QWORD [rbp + -32]
        movsx r10, DWORD [rbp + -16]
        add rbx, r10
        movzx rbx, BYTE [rbx]
        lea r10, QWORD [rbp + -12] ; get address of 'tmp'
        mov BYTE [r10], bl
        
        mov rbx, QWORD [rbp + -32]
        movsx r10, DWORD [rbp + -24]
        add rbx, r10
        movsx r10, DWORD [rbp + -16]
        sub rbx, r10
        mov r10, 1
        sub rbx, r10
        movzx rbx, BYTE [rbx]
        mov r10, QWORD [rbp + -32]
        movsx r11, DWORD [rbp + -16]
        add r10, r11
        mov BYTE [r10], bl
        
        mov rbx, QWORD [rbp + -32]
        movsx r10, DWORD [rbp + -24]
        add rbx, r10
        movsx r10, DWORD [rbp + -16]
        sub rbx, r10
        mov r10, 1
        sub rbx, r10
        movzx r10, BYTE [rbp + -12]
        mov BYTE [rbx], r10b
        
        lea rbx, QWORD [rbp + -16] ; get address of 'i'
        mov r10, rbx
        movsx rbx, DWORD [rbx]
        mov r11, rbx
        inc r11
        mov DWORD [r10], r11d
        
    jmp L_loop4
    L_exit4:
    
    mov rbx, QWORD [rbp + -32]
    movsx r10, DWORD [rbp + -24]
    add rbx, r10
    mov r10, 32
    mov BYTE [rbx], r10b
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    mov rbx, QWORD [rbp + -32]
    mov rcx, rbx ; arg 1
    movsx rbx, DWORD [rbp + -24]
    mov r10, 1
    add rbx, r10
    mov rdx, rbx ; arg 2
    call print
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    xor rax, rax ; Default return value 0
    L_function_print_num_exit:
    mov rsp, rbp
    pop rbp
    ret
    

list_init:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    mov rbx, QWORD [rbp + 16]
    add rbx, 0 ; member offset 'length'
    mov r10, 0
    mov QWORD [rbx], r10
    
    mov rbx, QWORD [rbp + 16]
    add rbx, 8 ; member offset 'capacity'
    mov r10, 2
    mov QWORD [rbx], r10
    
    sub rsp, 32 ; reserve shadow space and 1 arguments
    mov rbx, QWORD [rbp + 16]
    add rbx, 8 ; member offset 'capacity'
    mov rbx, QWORD [rbx]
    mov r10, 4 ; sizeof 'i32'
    imul rbx, r10
    mov rcx, rbx ; arg 1
    call malloc
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    mov r10, QWORD [rbp + 16]
    add r10, 16 ; member offset 'data'
    mov QWORD [r10], rbx
    
    xor rax, rax ; Default return value 0
    L_function_list_init_exit:
    mov rsp, rbp
    pop rbp
    ret
    

list_push:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    mov DWORD [rbp + 24], edx ; push arg 1 
    sub rsp, 16 ; reserve stack space for 2 locals
    mov rbx, QWORD [rbp + 16]
    add rbx, 0 ; member offset 'length'
    mov rbx, QWORD [rbx]
    mov r10, QWORD [rbp + 16]
    add r10, 8 ; member offset 'capacity'
    mov r10, QWORD [r10]
    cmp rbx, r10
    sete bl
    and bl, 1
    movzx rbx, bl
    cmp rbx, 0
    je L_exit5
        mov rbx, QWORD [rbp + 16]
        add rbx, 8 ; member offset 'capacity'
        mov rbx, QWORD [rbx]
        mov r10, 2
        imul rbx, r10
        mov r10, QWORD [rbp + 16]
        add r10, 8 ; member offset 'capacity'
        mov QWORD [r10], rbx
        
        sub rsp, 32 ; reserve shadow space and 1 arguments
        mov rbx, QWORD [rbp + 16]
        add rbx, 8 ; member offset 'capacity'
        mov rbx, QWORD [rbx]
        mov r10, 4 ; sizeof 'i32'
        imul rbx, r10
        mov rcx, rbx ; arg 1
        call malloc
        add rsp, 32 ; pop arguments
        mov rbx, rax ; get return value
        lea r10, QWORD [rbp + -16] ; get address of 'new_data'
        mov QWORD [r10], rbx
        
        mov DWORD [rbp + -8], 0 ; zero initialize 'i'
        
        L_loop6:
        mov rbx, QWORD [rbp + 16]
        add rbx, 0 ; member offset 'length'
        mov rbx, QWORD [rbx]
        movsx r10, DWORD [rbp + -8]
        cmp r10, rbx
        setl r10b
        and r10b, 1
        movzx r10, r10b
        cmp r10, 0
        je L_exit6
            lea rbx, QWORD [rbp + -16] ; get address of 'new_data'
            movsx r10, DWORD [rbp + -8]
            mov rbx, QWORD [rbx]
            imul r10, 4
            add rbx, r10
            mov r10, QWORD [rbp + 16]
            add r10, 16 ; member offset 'data'
            movsx r11, DWORD [rbp + -8]
            mov r10, QWORD [r10]
            imul r11, 4
            add r10, r11
            movsx r10, DWORD [r10]
            mov DWORD [rbx], r10d
            
            lea rbx, QWORD [rbp + -8] ; get address of 'i'
            mov r10, rbx
            movsx rbx, DWORD [rbx]
            mov r11, rbx
            inc r11
            mov DWORD [r10], r11d
            
        jmp L_loop6
        L_exit6:
        
        sub rsp, 32 ; reserve shadow space and 1 arguments
        mov rbx, QWORD [rbp + 16]
        add rbx, 16 ; member offset 'data'
        mov rbx, QWORD [rbx]
        mov rcx, rbx ; arg 1
        call free
        add rsp, 32 ; pop arguments
        mov rbx, rax ; get return value
        
        mov rbx, QWORD [rbp + 16]
        add rbx, 16 ; member offset 'data'
        mov r10, QWORD [rbp + -16]
        mov QWORD [rbx], r10
        
    L_exit5:
    
    mov rbx, QWORD [rbp + 16]
    add rbx, 0 ; member offset 'length'
    mov r10, rbx
    mov rbx, QWORD [rbx]
    mov r11, rbx
    inc r11
    mov QWORD [r10], r11
    mov r10, QWORD [rbp + 16]
    add r10, 16 ; member offset 'data'
    mov r10, QWORD [r10]
    imul rbx, 4
    add r10, rbx
    movsx rbx, DWORD [rbp + 24]
    mov DWORD [r10], ebx
    
    xor rax, rax ; Default return value 0
    L_function_list_push_exit:
    mov rsp, rbp
    pop rbp
    ret
    

main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 32 ; reserve stack space for 2 locals
    lea rdi, QWORD [rbp + -32] ; zero initialize 'list'
    xor rax, rax
    mov ecx, 24
    rep stosb
    
    sub rsp, 32 ; reserve shadow space and 1 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    call list_init
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    mov rbx, 3
    mov rdx, rbx ; arg 2
    call list_push
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    mov rbx, 1
    mov rdx, rbx ; arg 2
    call list_push
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    mov rbx, 4
    mov rdx, rbx ; arg 2
    call list_push
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    mov rbx, 1
    mov rdx, rbx ; arg 2
    call list_push
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    mov rbx, 5
    mov rdx, rbx ; arg 2
    call list_push
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    mov rbx, 9
    mov rdx, rbx ; arg 2
    call list_push
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    mov rbx, 2
    mov rdx, rbx ; arg 2
    call list_push
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    mov rbx, 6
    mov rdx, rbx ; arg 2
    call list_push
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    mov rbx, 5
    mov rdx, rbx ; arg 2
    call list_push
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    mov rbx, 3
    mov rdx, rbx ; arg 2
    call list_push
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    sub rsp, 32 ; reserve shadow space and 2 arguments
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    mov rcx, rbx ; arg 1
    mov rbx, 5
    mov rdx, rbx ; arg 2
    call list_push
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    mov DWORD [rbp + -8], 0 ; zero initialize 'i'
    
    L_loop7:
    lea rbx, QWORD [rbp + -32] ; get address of 'list'
    add rbx, 0 ; member offset 'length'
    mov rbx, QWORD [rbx]
    movsx r10, DWORD [rbp + -8]
    cmp r10, rbx
    setl r10b
    and r10b, 1
    movzx r10, r10b
    cmp r10, 0
    je L_exit7
        sub rsp, 32 ; reserve shadow space and 1 arguments
        lea rbx, QWORD [rbp + -32] ; get address of 'list'
        add rbx, 16 ; member offset 'data'
        movsx r10, DWORD [rbp + -8]
        mov rbx, QWORD [rbx]
        imul r10, 4
        add rbx, r10
        movsx rbx, DWORD [rbx]
        mov rcx, rbx ; arg 1
        call print_num
        add rsp, 32 ; pop arguments
        mov rbx, rax ; get return value
        
        lea rbx, QWORD [rbp + -8] ; get address of 'i'
        mov r10, rbx
        movsx rbx, DWORD [rbx]
        mov r11, rbx
        inc r11
        mov DWORD [r10], r11d
        
    jmp L_loop7
    L_exit7:
    
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    


SECTION .data
NULL dq 0
heap dq 0
STD_OUTPUT_HANDLE dq -11
lit_str_3 db "         ", 0
