; Generated by Lang compiler

extern GetCommandLineA
extern ExitProcess

section .code
global _start
_start:
    call GetCommandLineA
    mov rcx, rax
    call main
    mov ecx, eax
    call ExitProcess

main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 16 ; reserve stack space for 2 locals
    
    ; let a: i32; a = 321 % 43;
    mov rbx, 321
    mov r10, 43
    mov rax, rbx
    cqo
    idiv r10
    mov rbx, rdx
    lea r10, QWORD [rbp + -16] ; get address of 'a'
    mov DWORD [r10], ebx
    
    ; let b: i32; b = 3 % 5;
    mov rbx, 3
    mov r10, 5
    mov rax, rbx
    cqo
    idiv r10
    mov rbx, rdx
    lea r10, QWORD [rbp + -12] ; get address of 'b'
    mov DWORD [r10], ebx
    
    ; return a % b
    movsx rbx, DWORD [rbp + -16]
    movsx r10, DWORD [rbp + -12]
    mov rax, rbx
    cqo
    idiv r10
    mov rbx, rdx
    mov rax, rbx ; return via rax
    jmp L_function_main_exit
    
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    


section .data
