; Generated by Lang compiler

extern GetCommandLineA
extern ExitProcess

section .code
global _start
_start:
    call GetCommandLineA
    mov r10, rax
    xor rcx, rcx
    sub rsp, 8 * 64 ; Max 64 command line args
    mov rdx, rsp
    arg_loop_top:
    mov bl, BYTE [rax]
    test bl, bl
    jz arg_loop_exit
    cmp bl, ' '
    jne arg_loop_next
    cmp r10, rax
    je skip
    mov BYTE [rax], 0
    mov QWORD [rdx], r10
    add rdx, 8
    inc rcx
    skip:
    mov r10, rax
    inc r10
    arg_loop_next:
    inc rax
    jmp arg_loop_top
    arg_loop_exit:
    mov al, BYTE [r10]
    cmp al, ' '
    je args_done
    cmp al, 0
    je args_done
    mov QWORD [rdx], r10
    inc rcx
    args_done:
    mov rdx, rsp
    sub rsp, 32
    call main
    mov ecx, eax
    call ExitProcess

main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 16 ; reserve stack space for 2 locals
    
    ; let a: Val[2];
    mov QWORD [rbp + -16], 0 ; zero initialize 'a'
    
    ; let b: Arr;
    lea rdi, QWORD [rbp + -8] ; zero initialize 'b'
    xor rax, rax
    mov ecx, 8
    rep stosb
    
    ; a[1].val = 2
    lea rbx, QWORD [rbp + -16] ; get address of 'a'
    mov r10, 1
    imul r10, 4
    add rbx, r10
    add rbx, 0 ; member offset 'val'
    mov r10, 2
    mov DWORD [rbx], r10d
    
    ; b.vals[1] = 3
    lea rbx, QWORD [rbp + -8] ; get address of 'b'
    add rbx, 0 ; member offset 'vals'
    mov r10, 1
    imul r10, 4
    add rbx, r10
    mov r10, 3
    mov DWORD [rbx], r10d
    
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    


section .data
