; Generated by Lang compiler

extern GetCommandLineA
extern ExitProcess

section .code
global _start
_start:
    call GetCommandLineA
    mov r10, rax
    xor rcx, rcx
    sub rsp, 8 * 64 ; Max 64 command line args
    mov rdx, rsp
    arg_loop_top:
    mov bl, BYTE [rax]
    test bl, bl
    jz arg_loop_exit
    cmp bl, ' '
    jne arg_loop_next
    cmp r10, rax
    je skip
    mov BYTE [rax], 0
    mov QWORD [rdx], r10
    add rdx, 8
    inc rcx
    skip:
    mov r10, rax
    inc r10
    arg_loop_next:
    inc rax
    jmp arg_loop_top
    arg_loop_exit:
    mov al, BYTE [r10]
    cmp al, ' '
    je args_done
    cmp al, 0
    je args_done
    mov QWORD [rdx], r10
    inc rcx
    args_done:
    mov rdx, rsp
    sub rsp, 32
    call main
    mov ecx, eax
    call ExitProcess

extern ExitProcess

fail:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    
    ; ExitProcess(-1)
    sub rsp, 32 ; reserve shadow space and 1 arguments
    mov rbx, -1
    mov rcx, rbx ; arg 1
    call ExitProcess
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    xor rax, rax ; Default return value 0
    L_function_fail_exit:
    mov rsp, rbp
    pop rbp
    ret
    

main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 16 ; reserve stack space for 1 locals
    
    ; let stat: bool; stat = false && fail();
    mov rbx, 0
    test rbx, rbx
    je L_land_false_0 ; short circuit '&&'
    push rbx ; preserve
    sub rsp, 32 ; reserve shadow space and 0 arguments
    call fail
    add rsp, 32 ; pop arguments
    pop rbx ; restore
    mov r10, rax ; get return value
    test r10, r10
    je L_land_false_0
    mov rbx, 1
    jmp L_land_exit_0
    L_land_false_0:
    mov rbx, 0
    L_land_exit_0:
    lea r10, QWORD [rbp + -16] ; get address of 'stat'
    mov BYTE [r10], bl
    
    ; if (true || fail())
    mov rbx, 1
    test rbx, rbx
    jne L_lor_true_1 ; short circuit '||'
    push rbx ; preserve
    sub rsp, 32 ; reserve shadow space and 0 arguments
    call fail
    add rsp, 32 ; pop arguments
    pop rbx ; restore
    mov r10, rax ; get return value
    test r10, r10
    jne L_lor_true_1
    mov rbx, 0
    jmp L_lor_exit_1
    L_lor_true_1:
    mov rbx, 1
    L_lor_exit_1:
    cmp rbx, 0
    je L_exit2
    L_exit2:
    
    ; return 0
    mov rbx, 0
    mov rax, rbx ; return via rax
    jmp L_function_main_exit
    
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    


section .data
