; Generated by Lang compiler

GLOBAL main

SECTION .code
main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 16 ; reserve stack space for locals
    mov rbx, 1
    mov QWORD [rbp + -8], rbx; initialize a
    mov QWORD [rbp + -16], 0; zero initialize b
    mov rbx, QWORD [rbp + -8] ; get value of a
    mov r10, 0
    cmp rbx, r10
    jle L0
    mov rbx, 1
    jmp L1
    L0:
    mov rbx, 0
    L1:
    cmp rbx, 0
    je L_else2
        lea rbx, QWORD [rbp + -16] ; get address of b
        mov r10, 3
        mov QWORD [rbx], r10
    jmp L_exit2
    L_else2:
        lea rbx, QWORD [rbp + -16] ; get address of b
        mov r10, 2
        mov QWORD [rbx], r10
    L_exit2:
    mov rbx, QWORD [rbp + -16] ; get value of b
    mov rax, rbx ; return via rax
    jmp L_function_main_exit
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    
SECTION .data
