; Generated by Lang compiler

GLOBAL main

SECTION .code
main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 32 ; reserve stack space for locals
    mov rbx, 48
    mov QWORD [rbp + -8], rbx; initialize a
    mov rbx, 3
    mov QWORD [rbp + -16], rbx; initialize b
    mov rbx, QWORD [rbp + -8] ; get value of a
    mov r10, QWORD [rbp + -16] ; get value of b
    mov rax, rbx
    cdq
    idiv r10
    mov rbx, rax
    mov QWORD [rbp + -24], rbx; initialize c
    mov rbx, QWORD [rbp + -24] ; get value of c
    mov r10, 16
    cmp rbx, r10
    je L0
    mov rbx, 1
    jmp L1
    L0:
    mov rbx, 0
    L1:
    cmp rbx, 0
    je L_exit2
        mov rbx, 0
        mov rax, rbx ; return via rax
        jmp L_function_main_exit
    L_exit2:
    lea rbx, QWORD [rbp + -16] ; get address of b
    mov r10, 4
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -24] ; get value of c
    mov r10, QWORD [rbp + -16] ; get value of b
    mov rax, rbx
    cdq
    idiv r10
    mov rbx, rax
    lea r10, QWORD [rbp + -24] ; get address of c
    mov QWORD [r10], rbx
    mov rbx, QWORD [rbp + -24] ; get value of c
    mov r10, 4
    cmp rbx, r10
    je L3
    mov rbx, 1
    jmp L4
    L3:
    mov rbx, 0
    L4:
    cmp rbx, 0
    je L_exit5
        mov rbx, 0
        mov rax, rbx ; return via rax
        jmp L_function_main_exit
    L_exit5:
    mov rbx, QWORD [rbp + -24] ; get value of c
    mov r10, QWORD [rbp + -24] ; get value of c
    mov rax, rbx
    cdq
    idiv r10
    mov rbx, rax
    lea r10, QWORD [rbp + -24] ; get address of c
    mov QWORD [r10], rbx
    mov rbx, QWORD [rbp + -24] ; get value of c
    mov rax, rbx ; return via rax
    jmp L_function_main_exit
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    
SECTION .data
