; Generated by Lang compiler

GLOBAL main

SECTION .code
EXTERN OpenFile


EXTERN WriteFile


EXTERN CloseHandle


EXTERN strlen








main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 176 ; reserve stack space for 7 locals
    lea rbx, QWORD [rbp + -176] ; get address of 'file_name'
    lea r10, [REL lit_str_6]
    mov QWORD [rbx], r10
    
    lea rdi, QWORD [rbp + -168] ; zero initialize 'ofstruct'
    xor rax, rax
    mov ecx, 136
    rep stosb
    
    sub rsp, 32 ; reserve shadow space and 3 arguments
    mov rbx, QWORD [rbp + -176]
    mov rcx, rbx ; arg 0
    lea rbx, QWORD [rbp + -168] ; get address of 'ofstruct'
    mov rdx, rbx ; arg 1
    mov ebx, DWORD [REL OF_CREATE]
    mov r10d, DWORD [REL OF_READ]
    or rbx, r10
    mov r8, rbx ; arg 2
    call OpenFile
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    lea r10, QWORD [rbp + -32] ; get address of 'file_handle'
    mov QWORD [r10], rbx
    
    mov rbx, -1
    mov r10, QWORD [rbp + -32]
    cmp r10, rbx
    sete r10b
    and r10b, 1
    movzx r10, r10b
    cmp r10, 0
    je L_exit0
        mov rbx, -1
        mov rax, rbx ; return via rax
        jmp L_function_main_exit
        
    L_exit0:
    
    lea rbx, QWORD [rbp + -168] ; get address of 'ofstruct'
    add rbx, 8 ; member offset 'szPathName'
    lea r10, QWORD [rbp + -24] ; get address of 'path'
    mov QWORD [r10], rbx
    
    sub rsp, 32 ; reserve shadow space and 1 arguments
    mov rbx, QWORD [rbp + -24]
    mov rcx, rbx ; arg 0
    call strlen
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    lea r10, QWORD [rbp + -16] ; get address of 'path_len'
    mov DWORD [r10], ebx
    
    mov DWORD [rbp + -12], 0 ; zero initialize 'bytes_written'
    
    sub rsp, 48 ; reserve shadow space and 5 arguments
    mov rbx, QWORD [rbp + -32]
    mov rcx, rbx ; arg 0
    mov rbx, QWORD [rbp + -24]
    mov rdx, rbx ; arg 1
    movsx rbx, DWORD [rbp + -16]
    mov r8, rbx ; arg 2
    lea rbx, QWORD [rbp + -12] ; get address of 'bytes_written'
    mov r9, rbx ; arg 3
    mov rbx, 0
    mov QWORD [rsp + 32], rbx ; arg 4
    call WriteFile
    add rsp, 48 ; pop arguments
    mov rbx, rax ; get return value
    lea r10, QWORD [rbp + -8] ; get address of 'err'
    mov BYTE [r10], bl
    
    sub rsp, 32 ; reserve shadow space and 1 arguments
    mov rbx, QWORD [rbp + -32]
    mov rcx, rbx ; arg 0
    call CloseHandle
    add rsp, 32 ; pop arguments
    mov rbx, rax ; get return value
    
    movzx rbx, BYTE [rbp + -8]
    mov r10, 0
    cmp rbx, r10
    sete bl
    and bl, 1
    movzx rbx, bl
    cmp rbx, 0
    je L_exit1
        mov rbx, -1
        mov rax, rbx ; return via rax
        jmp L_function_main_exit
        
    L_exit1:
    
    mov rbx, 0
    mov rax, rbx ; return via rax
    jmp L_function_main_exit
    
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    


SECTION .data
NULL dq 0
GENERIC_WRITE dq 1073741824
CREATE_NEW dq 1
FILE_ATTRIBUTE_NORMAL dq 128
OF_CREATE dq 4096
OF_READ dq 0
lit_str_6 db "TEST.TXT", 0
