; Generated by Lang compiler

GLOBAL main

SECTION .code
one:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    sub rsp, 0 ; reserve stack space for locals
    mov rbx, QWORD [rbp + 16] ; get value of arg
    mov r10, 1
    add rbx, r10
    mov rax, rbx ; return via rax
    jmp L_function_one_exit
    xor rax, rax ; Default return value 0
    L_function_one_exit:
    mov rsp, rbp
    pop rbp
    ret
    
two:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    mov QWORD [rbp + 24], rdx ; push arg 1 
    sub rsp, 16 ; reserve stack space for locals
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [rbp + 16] ; get value of a
    mov rcx, rbx ; arg 0
    call one
    mov rbx, rax ; get return value
    mov QWORD [rbp + -8], rbx; initialize local
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [rbp + 24] ; get value of b
    mov rcx, rbx ; arg 0
    call one
    mov rbx, rax ; get return value
    mov r10, QWORD [rbp + -8] ; get value of local
    add rbx, r10
    mov rax, rbx ; return via rax
    jmp L_function_two_exit
    xor rax, rax ; Default return value 0
    L_function_two_exit:
    mov rsp, rbp
    pop rbp
    ret
    
recursive:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    mov QWORD [rbp + 24], rdx ; push arg 1 
    sub rsp, 0 ; reserve stack space for locals
    mov rbx, QWORD [rbp + 16] ; get value of a
    mov r10, 0
    cmp rbx, r10
    jne L0
    mov rbx, 1
    jmp L1
    L0:
    mov rbx, 0
    L1:
    cmp rbx, 0
    je L_exit2
        mov rbx, QWORD [rbp + 24] ; get value of b
        mov rax, rbx ; return via rax
        jmp L_function_recursive_exit
    L_exit2:
    mov rbx, QWORD [rbp + 24] ; get value of b
    mov r10, 2
    add rbx, r10
    lea r10, QWORD [rbp + 24] ; get address of b
    mov QWORD [r10], rbx
    mov rbx, QWORD [rbp + 16] ; get value of a
    mov r10, 1
    sub rbx, r10
    lea r10, QWORD [rbp + 16] ; get address of a
    mov QWORD [r10], rbx
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [rbp + 16] ; get value of a
    mov rcx, rbx ; arg 0
    mov rbx, QWORD [rbp + 24] ; get value of b
    mov rdx, rbx ; arg 1
    call recursive
    mov rbx, rax ; get return value
    mov rax, rbx ; return via rax
    jmp L_function_recursive_exit
    xor rax, rax ; Default return value 0
    L_function_recursive_exit:
    mov rsp, rbp
    pop rbp
    ret
    
main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 16 ; reserve stack space for locals
    sub rsp, 32 ; shadow space
    mov rbx, 1
    mov rcx, rbx ; arg 0
    mov rbx, 2
    mov rdx, rbx ; arg 1
    call two
    mov rbx, rax ; get return value
    mov QWORD [rbp + -8], rbx; initialize bla
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [rbp + -8] ; get value of bla
    mov rcx, rbx ; arg 0
    call one
    mov rbx, rax ; get return value
    mov QWORD [rbp + -16], rbx; initialize tmp
    sub rsp, 32 ; shadow space
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [rbp + -8] ; get value of bla
    mov rcx, rbx ; arg 0
    call one
    mov rbx, rax ; get return value
    mov rcx, rbx ; arg 0
    mov rbx, 0
    mov rdx, rbx ; arg 1
    call recursive
    mov rbx, rax ; get return value
    mov rax, rbx ; return via rax
    jmp L_function_main_exit
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    
SECTION .data
