; Generated by Lang compiler

GLOBAL main

SECTION .code
EXTERN GetProcessHeap

EXTERN HeapAlloc

EXTERN HeapFree

EXTERN GetStdHandle

EXTERN WriteFile

EXTERN ExitProcess

malloc:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    sub rsp, 0 ; reserve stack space for locals
    mov rbx, QWORD [REL heap] ; get value of heap
    mov r10, QWORD [REL NULL] ; get value of NULL
    cmp rbx, r10
    jne L0
    mov rbx, 1
    jmp L1
    L0:
    mov rbx, 0
    L1:
    cmp rbx, 0
    je L_exit2
        lea rbx, QWORD [REL heap] ; get address of heap
        sub rsp, 32 ; shadow space
        call GetProcessHeap
        mov r10, rax ; get return value
        mov QWORD [rbx], r10
    L_exit2:
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [REL heap] ; get value of heap
    mov rcx, rbx ; arg 0
    mov rbx, 0
    mov rdx, rbx ; arg 1
    mov rbx, QWORD [rbp + 16] ; get value of size
    mov r8, rbx ; arg 2
    call HeapAlloc
    mov rbx, rax ; get return value
    mov rax, rbx ; return via rax
    jmp L_function_malloc_exit
    xor rax, rax ; Default return value 0
    L_function_malloc_exit:
    mov rsp, rbp
    pop rbp
    ret
    
free:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    sub rsp, 0 ; reserve stack space for locals
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [rbp + 16] ; get value of ptr
    mov r10, QWORD [REL NULL] ; get value of NULL
    cmp rbx, r10
    je L3
    mov rbx, 1
    jmp L4
    L3:
    mov rbx, 0
    L4:
    mov rcx, rbx ; arg 0
    call assert
    mov rbx, rax ; get return value
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [REL heap] ; get value of heap
    mov r10, QWORD [REL NULL] ; get value of NULL
    cmp rbx, r10
    je L5
    mov rbx, 1
    jmp L6
    L5:
    mov rbx, 0
    L6:
    mov rcx, rbx ; arg 0
    call assert
    mov rbx, rax ; get return value
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [REL heap] ; get value of heap
    mov rcx, rbx ; arg 0
    mov rbx, 0
    mov rdx, rbx ; arg 1
    mov rbx, QWORD [rbp + 16] ; get value of ptr
    mov r8, rbx ; arg 2
    call HeapFree
    mov rbx, rax ; get return value
    xor rax, rax ; Default return value 0
    L_function_free_exit:
    mov rsp, rbp
    pop rbp
    ret
    
assert:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    sub rsp, 0 ; reserve stack space for locals
    mov rbx, QWORD [rbp + 16] ; get value of expression
    test rbx, rbx
    jne L_lnot_false_7
    mov rbx, 1
    jmp L_lnot_exit_7
    L_lnot_false_7:
    mov rbx, 0
    L_lnot_exit_7:
    cmp rbx, 0
    je L_exit8
        sub rsp, 32 ; shadow space
        mov rbx, 1
        mov rcx, rbx ; arg 0
        call ExitProcess
        mov rbx, rax ; get return value
    L_exit8:
    xor rax, rax ; Default return value 0
    L_function_assert_exit:
    mov rsp, rbp
    pop rbp
    ret
    
print:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    mov QWORD [rbp + 24], rdx ; push arg 1 
    sub rsp, 16 ; reserve stack space for locals
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [REL STD_OUTPUT_HANDLE] ; get value of STD_OUTPUT_HANDLE
    mov rcx, rbx ; arg 0
    call GetStdHandle
    mov rbx, rax ; get return value
    mov QWORD [rbp + -8], rbx; initialize std_handle
    mov QWORD [rbp + -16], 0; zero initialize bytes_written
    sub rsp, 32 + 1 * 8 + 8 ; shadow space + spill arguments + alignment
    mov rbx, QWORD [rbp + -8] ; get value of std_handle
    mov rcx, rbx ; arg 0
    mov rbx, QWORD [rbp + 16] ; get value of str
    mov rdx, rbx ; arg 1
    mov rbx, QWORD [rbp + 24] ; get value of str_len
    mov r8, rbx ; arg 2
    lea rbx, QWORD [rbp + -16] ; addrof bytes_written
    mov r9, rbx ; arg 3
    mov rbx, QWORD [REL NULL] ; get value of NULL
    mov QWORD [rsp + 4 * 8], rbx ; arg 4
    call WriteFile
    mov rbx, rax ; get return value
    xor rax, rax ; Default return value 0
    L_function_print_exit:
    mov rsp, rbp
    pop rbp
    ret
    
strlen:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    mov QWORD [rbp + 16], rcx ; push arg 0 
    sub rsp, 16 ; reserve stack space for locals
    mov rbx, 0
    mov QWORD [rbp + -8], rbx; initialize len
    L_loop9:
    mov rbx, QWORD [rbp + 16] ; get value of str
    mov r10, QWORD [rbp + -8] ; get value of len
    add rbx, r10
    mov rbx, QWORD [rbx]
    mov r10, QWORD [REL NULL] ; get value of NULL
    cmp rbx, r10
    je L10
    mov rbx, 1
    jmp L11
    L10:
    mov rbx, 0
    L11:
    cmp rbx, 0
    je L_exit9
        mov rbx, QWORD [rbp + -8] ; get value of len
        mov r10, 1
        add rbx, r10
        lea r10, QWORD [rbp + -8] ; get address of len
        mov QWORD [r10], rbx
    jmp L_loop9
    L_exit9:
    mov rbx, QWORD [rbp + -8] ; get value of len
    mov rax, rbx ; return via rax
    jmp L_function_strlen_exit
    xor rax, rax ; Default return value 0
    L_function_strlen_exit:
    mov rsp, rbp
    pop rbp
    ret
    
main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 32 ; reserve stack space for locals
    sub rsp, 32 ; shadow space
    mov rbx, 16
    mov rcx, rbx ; arg 0
    call malloc
    mov rbx, rax ; get return value
    mov QWORD [rbp + -8], rbx; initialize mem
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov r10, 0
    add rbx, r10
    mov r10, 66
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov r10, 1
    add rbx, r10
    mov r10, 114
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov r10, 2
    add rbx, r10
    mov r10, 117
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov r10, 3
    add rbx, r10
    mov r10, 104
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov r10, 4
    add rbx, r10
    mov r10, 84
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov r10, 5
    add rbx, r10
    mov r10, 101
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov r10, 6
    add rbx, r10
    mov r10, 115
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov r10, 7
    add rbx, r10
    mov r10, 116
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov r10, 8
    add rbx, r10
    mov r10, 0
    mov QWORD [rbx], r10
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov rcx, rbx ; arg 0
    call strlen
    mov rbx, rax ; get return value
    mov QWORD [rbp + -16], rbx; initialize str_len
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov rcx, rbx ; arg 0
    mov rbx, QWORD [rbp + -16] ; get value of str_len
    mov rdx, rbx ; arg 1
    call print
    mov rbx, rax ; get return value
    sub rsp, 32 ; shadow space
    mov rbx, QWORD [rbp + -8] ; get value of mem
    mov rcx, rbx ; arg 0
    call free
    mov rbx, rax ; get return value
    sub rsp, 32 ; shadow space
    mov rbx, 16
    mov rcx, rbx ; arg 0
    call malloc
    mov rbx, rax ; get return value
    mov QWORD [rbp + -24], rbx; initialize mem2
    mov rbx, QWORD [rbp + -24] ; get value of mem2
    mov r10, 0
    add rbx, r10
    mov r10, 1
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -24] ; get value of mem2
    mov r10, 1
    add rbx, r10
    mov r10, 2
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -24] ; get value of mem2
    mov r10, 2
    add rbx, r10
    mov r10, 3
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -24] ; get value of mem2
    mov r10, 3
    add rbx, r10
    mov r10, 4
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -24] ; get value of mem2
    mov r10, 4
    add rbx, r10
    mov r10, 0
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -24] ; get value of mem2
    mov r10, 5
    add rbx, r10
    mov r10, 0
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -24] ; get value of mem2
    mov r10, 6
    add rbx, r10
    mov r10, 0
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -24] ; get value of mem2
    mov r10, 7
    add rbx, r10
    mov r10, 0
    mov QWORD [rbx], r10
    mov rbx, QWORD [rbp + -24] ; get value of mem2
    mov rbx, QWORD [rbx]
    mov rax, rbx ; return via rax
    jmp L_function_main_exit
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    
SECTION .data
NULL dq 0
heap dq 0
STD_OUTPUT_HANDLE dq -11
