; Generated by Lang compiler

GLOBAL main

SECTION .code
main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 16 ; reserve stack space for 2 locals
    mov rbx, 321
    mov r10, 43
    mov rax, rbx
    cqo
    idiv r10
    mov rbx, rdx
    lea r10, QWORD [rbp + -16] ; get address of 'a'
    mov DWORD [r10], ebx
    
    mov rbx, 3
    mov r10, 5
    mov rax, rbx
    cqo
    idiv r10
    mov rbx, rdx
    lea r10, QWORD [rbp + -12] ; get address of 'b'
    mov DWORD [r10], ebx
    
    movsx rbx, DWORD [rbp + -16]
    movsx r10, DWORD [rbp + -12]
    mov rax, rbx
    cqo
    idiv r10
    mov rbx, rdx
    mov rax, rbx ; return via rax
    jmp L_function_main_exit
    
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    


SECTION .data
