; Generated by Lang compiler

GLOBAL main

SECTION .code
main:
    push rbp ; save RBP
    mov rbp, rsp ; stack frame
    sub rsp, 32 ; reserve stack space for locals
    mov rbx, 2
    mov BYTE [rbp + -1], bl; initialize signed_8
    mov rbx, 127
    mov r10, 53
    add rbx, r10
    mov WORD [rbp + -3], bx; initialize signed_16
    mov rbx, 32767
    mov r10, 2364
    add rbx, r10
    mov DWORD [rbp + -7], ebx; initialize signed_32
    mov rbx, 238643254
    mov r10, 2147483647
    sub rbx, r10
    mov QWORD [rbp + -15], rbx; initialize signed_64
    mov rbx, 2
    mov BYTE [rbp + -16], bl; initialize unsigned_8
    mov rbx, 256
    mov r10, 53
    add rbx, r10
    mov WORD [rbp + -18], bx; initialize unsigned_16
    mov rbx, 65536
    mov r10, 2364
    add rbx, r10
    mov DWORD [rbp + -22], ebx; initialize unsigned_32
    mov rbx, 0
    mov r10, 238643254
    add rbx, r10
    mov QWORD [rbp + -30], rbx; initialize unsigned_64
    xor rax, rax ; Default return value 0
    L_function_main_exit:
    mov rsp, rbp
    pop rbp
    ret
    
SECTION .data
